### ISSUE TITLE
Blank page after click on product name

### ISSUE THREAD

**Issue by PrzemekSkw** [IndomaximTechID/storaji#12]
When I click on Products and then on specific name sometimes I have info about it but after one second it become empty like this:
![zrzut ekranu deepin_20180125082346](https://user-images.githubusercontent.com/25219988/35376175-26c648a8-01aa-11e8-845f-911e583086c1.png)
 and sometimes products list disapears and I must refresh or close app.

**Comment by lowsprofile** [comment]
This is happen when user has a low connection of internet or too much requesting another page frequently. when the app is requesting to the server and has long pending response from server it caused max exceed request per IP.

Since this version is not doing unsubscribe request if user try to request another page and still have pending responses, it will causes blank page.
The good things for now is before further information about this issue, **Don't navigate to another page very fast. Because it can make a lot of request to the server**.

I will fix this in the next release asap, this is very help me. @PrzemekSkw  thanks for report this, I really appreciated!! Because this is critical issue. Good job! :+1:

**Comment by PrzemekSkw** [comment]
Thanks, I noticed sometimes I click too fast :) but in last version it works better I think.

**Comment by lowsprofile** [comment]
Ok happy to hears that, but still as I said, this version doesn't have unsubscribe function to immediately cancel the request to the server if still has pending requests. And I will fix this asap since this is critical issue, please be patient to the next release, and don't do what I said before to keep the server alive :+1:

**Comment by PrzemekSkw** [comment]
OK, don't worry, You make great job :+1:

**Comment by lowsprofile** [comment]
Fixed on [^1.0.0-beta.9](https://github.com/IndomaximTechID/storaji/releases/tag/v1.0.0-beta.9)
